using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class InitializeSong : MonoBehaviour {

    static Bar dummyBar = new Bar(new List<Note>());
    static Bar firstBar = new Bar(new List<Note>() { new Note(1, Note.F_3, Note.Note_Types.quarter_note), new Note(2, Note.E_3, Note.Note_Types.quarter_note), new Note(3, Note.D_3, Note.Note_Types.quarter_note), new Note(4, Note.E_3, Note.Note_Types.quarter_note) });
    static Bar secondBar = new Bar(new List<Note>() { new Note(1, Note.F_3, Note.Note_Types.quarter_note), new Note(2, Note.F_3, Note.Note_Types.quarter_note), new Note(3, Note.F_3, Note.Note_Types.half_note) });
    static Bar thirdBar = new Bar(new List<Note>() { new Note(1, Note.C_3, Note.Note_Types.whole_note), /*new Note(1, Note.D_3, Note.Note_Types.eighth_note), */new Note(1.125f, Note.E_3, Note.Note_Types.eighth_note), new Note(1.25f, Note.F_3, Note.Note_Types.eighth_note), new Note(1.375f, Note.G_3, Note.Note_Types.eighth_note), new Note(1.5f, Note.A_3, Note.Note_Types.eighth_note), new Note(1.625f, Note.B_3, Note.Note_Types.eighth_note), new Note(1.75f, Note.C_4, Note.Note_Types.eighth_note), new Note(1.875f, Note.D_4, Note.Note_Types.eighth_note), new Note(2, Note.F_1, Note.Note_Types.eighth_note), new Note(2.125f, Note.G_1, Note.Note_Types.eighth_note), new Note(2.25f, Note.A_1, Note.Note_Types.eighth_note), new Note(2.375f, Note.B_1, Note.Note_Types.eighth_note), new Note(2.5f, Note.C_2, Note.Note_Types.eighth_note), new Note(2.625f, Note.D_2, Note.Note_Types.eighth_note), new Note(2.75f, Note.E_2, Note.Note_Types.eighth_note), new Note(2.875f, Note.F_2, Note.Note_Types.eighth_note), new Note(3.0f, Note.G_2, Note.Note_Types.eighth_note), new Note(3.125f, Note.A_2, Note.Note_Types.eighth_note) });
    static Bar fourthBar = new Bar(new List<Note>() { new Note(1, Note.Rest_Treble, Note.Note_Types.quarter_rest), new Note(2, Note.Rest_Bass, Note.Note_Types.whole_rest), new Note(2, Note.Rest_Treble, Note.Note_Types.half_rest), new Note(3, Note.Rest_Treble, Note.Note_Types.eighth_rest), new Note(3.5f, Note.Rest_Treble, Note.Note_Types.eighth_rest) });

    public static Song song = new Song(1, "Mary Had a Little Lamb", "I Don't Know", (int)Keys.cmaj, 4, 4, new List<Bar>() { dummyBar, firstBar, secondBar, thirdBar, fourthBar }, 60);
    
    static Bar Ode_1 = new Bar(new List<Note>() {new Note(1, Note.E_3, Note.Note_Types.quarter_note), new Note(2, Note.E_3, Note.Note_Types.quarter_note), new Note(3, Note.F_3, Note.Note_Types.quarter_note), new Note(4, Note.G_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.whole_note), new Note(1, Note.E_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_2 = new Bar(new List<Note>() { new Note(1, Note.G_3, Note.Note_Types.quarter_note), new Note(2, Note.F_3, Note.Note_Types.quarter_note), new Note(3, Note.E_3, Note.Note_Types.quarter_note), new Note(4, Note.D_3, Note.Note_Types.quarter_note), new Note(1, Note.B_1, Note.Note_Types.whole_note), new Note(1, Note.D_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_3 = new Bar(new List<Note>() { new Note(1, Note.C_3, Note.Note_Types.quarter_note), new Note(2, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.D_3, Note.Note_Types.quarter_note), new Note(4, Note.E_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.whole_note), new Note(1, Note.E_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_4 = new Bar(new List<Note>() { new Note(1, Note.E_3, Note.Note_Types.quarter_note), new Note(2, Note.D_3, Note.Note_Types.quarter_note), new Note(3, Note.D_3, Note.Note_Types.half_note), new Note(1, Note.C_2, Note.Note_Types.half_note), new Note(1, Note.E_2, Note.Note_Types.half_note), new Note(1, Note.G_2, Note.Note_Types.half_note), new Note(3, Note.B_1, Note.Note_Types.half_note), new Note(3, Note.D_2, Note.Note_Types.half_note), new Note(3, Note.G_2, Note.Note_Types.half_note) });
    static Bar Ode_5 = new Bar(new List<Note>() { new Note(1, Note.E_3, Note.Note_Types.quarter_note), new Note(2, Note.E_3, Note.Note_Types.quarter_note), new Note(3, Note.F_3, Note.Note_Types.quarter_note), new Note(4, Note.G_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.whole_note), new Note(1, Note.E_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_6 = new Bar(new List<Note>() { new Note(1, Note.G_3, Note.Note_Types.quarter_note), new Note(2, Note.F_3, Note.Note_Types.quarter_note), new Note(3, Note.E_3, Note.Note_Types.quarter_note), new Note(4, Note.D_3, Note.Note_Types.quarter_note), new Note(1, Note.B_1, Note.Note_Types.whole_note), new Note(1, Note.D_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_7 = new Bar(new List<Note>() { new Note(1, Note.C_3, Note.Note_Types.quarter_note), new Note(2, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.D_3, Note.Note_Types.quarter_note), new Note(4, Note.E_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.whole_note), new Note(1, Note.E_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_8 = new Bar(new List<Note>() { new Note(1, Note.D_3, Note.Note_Types.quarter_note), new Note(2, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.C_3, Note.Note_Types.half_note), new Note(3, Note.C_2, Note.Note_Types.half_note), new Note(3, Note.E_2, Note.Note_Types.half_note), new Note(3, Note.G_2, Note.Note_Types.half_note), new Note(1, Note.B_1, Note.Note_Types.half_note), new Note(1, Note.D_2, Note.Note_Types.half_note), new Note(1, Note.G_2, Note.Note_Types.half_note) });
    static Bar Ode_9 = new Bar(new List<Note>() { new Note(1, Note.D_3, Note.Note_Types.half_note), new Note(3, Note.E_3, Note.Note_Types.quarter_note), new Note(4, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.C_2, Note.Note_Types.half_note), new Note(3, Note.E_2, Note.Note_Types.half_note), new Note(3, Note.G_2, Note.Note_Types.half_note), new Note(1, Note.B_1, Note.Note_Types.half_note), new Note(1, Note.D_2, Note.Note_Types.half_note), new Note(1, Note.G_2, Note.Note_Types.half_note) });
    static Bar Ode_10 = new Bar(new List<Note>() { new Note(1, Note.D_3, Note.Note_Types.quarter_note), new Note(2, Note.E_3, Note.Note_Types.eighth_note), new Note(2.5f, Note.F_3, Note.Note_Types.eighth_note), new Note(3, Note.E_3, Note.Note_Types.quarter_note), new Note(4, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.C_2, Note.Note_Types.half_note), new Note(3, Note.E_2, Note.Note_Types.half_note), new Note(3, Note.G_2, Note.Note_Types.half_note), new Note(1, Note.B_1, Note.Note_Types.half_note), new Note(1, Note.D_2, Note.Note_Types.half_note), new Note(1, Note.G_2, Note.Note_Types.half_note) });
    static Bar Ode_11 = new Bar(new List<Note>() { new Note(1, Note.D_3, Note.Note_Types.quarter_note), new Note(2, Note.E_3, Note.Note_Types.eighth_note), new Note(2.5f, Note.F_3, Note.Note_Types.eighth_note), new Note(3, Note.E_3, Note.Note_Types.quarter_note), new Note(4, Note.D_3, Note.Note_Types.quarter_note), new Note(3, Note.C_2, Note.Note_Types.quarter_note), new Note(3, Note.E_2, Note.Note_Types.quarter_note), new Note(3, Note.G_2, Note.Note_Types.quarter_note), new Note(1, Note.B_1, Note.Note_Types.half_note), new Note(1, Note.D_2, Note.Note_Types.half_note), new Note(1, Note.G_2, Note.Note_Types.half_note), new Note(4, Note.B_1, Note.Note_Types.quarter_note), new Note(4, Note.D_2, Note.Note_Types.quarter_note), new Note(4, Note.G_2, Note.Note_Types.quarter_note) });
    static Bar Ode_12 = new Bar(new List<Note>() { new Note(1, Note.C_3, Note.Note_Types.half_note), new Note(2, Note.D_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.quarter_note), new Note(1, Note.E_2, Note.Note_Types.quarter_note), new Note(1, Note.G_2, Note.Note_Types.quarter_note), new Note(2, Note.B_1, Note.Note_Types.quarter_note), new Note(2, Note.D_2, Note.Note_Types.quarter_note), new Note(2, Note.G_2, Note.Note_Types.quarter_note), new Note(3, Note.B_1, Note.Note_Types.half_note), new Note(3, Note.D_2, Note.Note_Types.half_note), new Note(3, Note.G_2, Note.Note_Types.half_note) });
    static Bar Ode_13 = new Bar(new List<Note>() { new Note(1, Note.E_3, Note.Note_Types.quarter_note), new Note(2, Note.E_3, Note.Note_Types.quarter_note), new Note(3, Note.F_3, Note.Note_Types.quarter_note), new Note(4, Note.G_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.whole_note), new Note(1, Note.E_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_14 = new Bar(new List<Note>() { new Note(1, Note.G_3, Note.Note_Types.quarter_note), new Note(2, Note.F_3, Note.Note_Types.quarter_note), new Note(3, Note.E_3, Note.Note_Types.quarter_note), new Note(4, Note.D_3, Note.Note_Types.quarter_note), new Note(1, Note.B_1, Note.Note_Types.whole_note), new Note(1, Note.D_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_15 = new Bar(new List<Note>() { new Note(1, Note.C_3, Note.Note_Types.quarter_note), new Note(2, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.D_3, Note.Note_Types.quarter_note), new Note(4, Note.E_3, Note.Note_Types.quarter_note), new Note(1, Note.C_2, Note.Note_Types.whole_note), new Note(1, Note.E_2, Note.Note_Types.whole_note), new Note(1, Note.G_2, Note.Note_Types.whole_note) });
    static Bar Ode_16 = new Bar(new List<Note>() { new Note(1, Note.D_3, Note.Note_Types.quarter_note), new Note(2, Note.C_3, Note.Note_Types.quarter_note), new Note(3, Note.C_3, Note.Note_Types.half_note), new Note(3, Note.C_2, Note.Note_Types.half_note), new Note(3, Note.E_2, Note.Note_Types.half_note), new Note(3, Note.G_2, Note.Note_Types.half_note), new Note(1, Note.B_1, Note.Note_Types.half_note), new Note(1, Note.D_2, Note.Note_Types.half_note), new Note(1, Note.G_2, Note.Note_Types.half_note) });

    public static Song OdeToJoy = new Song(2, "Ode To Joy", "Beethoven", (int)Keys.cmaj, 4, 4, new List<Bar>() { dummyBar, Ode_1, Ode_2, Ode_3, Ode_4, Ode_5, Ode_6, Ode_7, Ode_8, Ode_9, Ode_10, Ode_11, Ode_12, Ode_13, Ode_14, Ode_15, Ode_16 }, 60);

    // Use this for initialization
    void Start () {
        Song.SetCurrentSong(OdeToJoy);
    }

    // Update is called once per frame
    void Update () {
	
	}
}
